local c = require 'meinz-scheme.colors'

return {
    DevIconPy = { ctermfg = c.yellow_01 },
    DevIconNotebook = { ctermfg = c.yellow_01 },
    DevIconPyc = { ctermfg = c.yellow_01 },
    DevIconPyd = { ctermfg = c.yellow_01 },
    DevIconPyi = { ctermfg = c.yellow_01 },
    DevIconPyo = { ctermfg = c.yellow_01 },
    DevIconPyx = { ctermfg = c.yellow_01 },
    DevIconLua = { ctermfg = c.blue_02 },

    DevIconGitAttributes = { ctermfg = c.red_01 },
    DevIconGitCommit = { ctermfg = c.red_01 },
    DevIconGitConfig = { ctermfg = c.red_01 },
    DevIconGitIgnore = { ctermfg = c.red_01 },
    DevIconGitModules = { ctermfg = c.red_01 },
    DevIconGitlabCI = { ctermfg = c.red_01 },

    DevIconCMakeLists = { ctermfg = c.cyan_01 },

    DevIconDockerfile = { ctermfg = c.blue_02 },
    DevIconEnv = { ctermfg = c.red_01 },

    DevIconSettingsJson = { ctermfg = c.red_01 },
    DevIconVimrc = { ctermfg = c.red_01 },
    DevIconTmux = { ctermfg = c.red_01 },

    DevIconZshenv = { ctermfg = c.red_01 },
    DevIconZshprofile = { ctermfg = c.red_01 },
    DevIconZshrc = { ctermfg = c.red_01 },
    DevIconMakefile = { ctermfg = c.red_01 },
    DevIconIni = { ctermfg = c.red_01 },
    DevIconBash = { ctermfg = c.green_01 },
    DevIconBazel = { ctermfg = c.green_01 },

    DevIconBin = { ctermfg = c.blue_01 },
    DevIconCMake = { ctermfg = c.red_01 },
    DevIconCPlusPlus = { ctermfg = c.blue_01 },
    DevIconC = { ctermfg = c.blue_01 },
    DevIconCpp = { ctermfg = c.blue_01 },
    DevIconCp = { ctermfg = c.blue_01 },
    DevIconCppm = { ctermfg = c.blue_01 },
    DevIconCxx = { ctermfg = c.blue_01 },
    DevIconCxxm = { ctermfg = c.blue_01 },
    DevIconGo = { ctermfg = c.blue_01 },
    DevIconJs = { ctermfg = c.yellow_01 },
    DevIconMts = { ctermfg = c.blue_01 },
    DevIconTypeScript = { ctermfg = c.blue_01 },
    DevIconRs = { ctermfg = c.red_01 },
    DevIconPsScriptfile = { ctermfg = c.green_01 },
    DevIconConfiguration = { ctermfg = c.red_01 },
    DevIconJson = { ctermfg = c.yellow_01 },
    DevIconJson5 = { ctermfg = c.yellow_01 },
    DevIconJsonc = { ctermfg = c.yellow_01 },
}
