local colors = require 'meinz-scheme.colors'
local c, tc = colors.termc, colors.truec

return {
  MiniIconsAzure    = { ctermfg = c.cyan, fg = tc.cyan },
  MiniIconsBlue     = { ctermfg = c.blue, fg = tc.blue },
  MiniIconsCyan     = { ctermfg = c.cyan, fg = tc.cyan },
  MiniIconsGreen    = { ctermfg = c.green, fg = tc.green },
  MiniIconsGrey     = { ctermfg = c.white_01, fg = tc.white_01 },
  MiniIconsOrange   = { ctermfg = c.orange, fg = tc.orange },
  MiniIconsPurple   = { ctermfg = c.magenta, fg = tc.magenta },
  MiniIconsRed      = { ctermfg = c.red, fg = tc.red },
  MiniIconsYellow   = { ctermfg = c.yellow, fg = tc.yellow },
  -- DevIconPy               = { ctermfg = c.yellow, fg = tc.yellow },
  -- DevIconNotebook         = { ctermfg = c.yellow, fg = tc.yellow },
  -- DevIconPyc              = { ctermfg = c.yellow, fg = tc.yellow },
  -- DevIconPyd              = { ctermfg = c.yellow, fg = tc.yellow },
  -- DevIconPyi              = { ctermfg = c.yellow, fg = tc.yellow },
  -- DevIconPyo              = { ctermfg = c.yellow, fg = tc.yellow },
  -- DevIconPyx              = { ctermfg = c.yellow, fg = tc.yellow },
  -- DevIconLua              = { ctermfg = c.blue, fg = tc.blue },
  --
  -- DevIconGitAttributes    = { ctermfg = c.red, fg = tc.red },
  -- DevIconGitCommit        = { ctermfg = c.red, fg = tc.red },
  -- DevIconGitConfig        = { ctermfg = c.red, fg = tc.red },
  -- DevIconGitIgnore        = { ctermfg = c.red, fg = tc.red },
  -- DevIconGitModules       = { ctermfg = c.red, fg = tc.red },
  -- DevIconGitlabCI         = { ctermfg = c.red, fg = tc.red },
  --
  -- DevIconCMakeLists       = { ctermfg = c.cyan, fg = tc.cyan },
  --
  -- DevIconDockerfile       = { ctermfg = c.blue, fg = tc.blue },
  -- DevIconEnv              = { ctermfg = c.red, fg = tc.red },
  --
  -- DevIconSettingsJson     = { ctermfg = c.red, fg = tc.red },
  -- DevIconVimrc            = { ctermfg = c.red, fg = tc.red },
  -- DevIconTmux             = { ctermfg = c.red, fg = tc.red },
  --
  -- DevIconZshenv           = { ctermfg = c.red, fg = tc.red },
  -- DevIconZshprofile       = { ctermfg = c.red, fg = tc.red },
  -- DevIconZshrc            = { ctermfg = c.red, fg = tc.red },
  -- DevIconMakefile         = { ctermfg = c.red, fg = tc.red },
  -- DevIconIni              = { ctermfg = c.red, fg = tc.red },
  -- DevIconBash             = { ctermfg = c.green, fg = tc.green },
  -- DevIconBazel            = { ctermfg = c.green, fg = tc.green },
  --
  -- DevIconBin              = { ctermfg = c.blue, fg = tc.blue },
  -- DevIconCMake            = { ctermfg = c.red, fg = tc.red },
  -- DevIconCPlusPlus        = { ctermfg = c.blue, fg = tc.blue },
  -- DevIconC                = { ctermfg = c.blue, fg = tc.blue },
  -- DevIconCpp              = { ctermfg = c.blue, fg = tc.blue },
  -- DevIconCp               = { ctermfg = c.blue, fg = tc.blue },
  -- DevIconCppm             = { ctermfg = c.blue, fg = tc.blue },
  -- DevIconCxx              = { ctermfg = c.blue, fg = tc.blue },
  -- DevIconCxxm             = { ctermfg = c.blue, fg = tc.blue },
  -- DevIconGo               = { ctermfg = c.blue, fg = tc.blue },
  -- DevIconJs               = { ctermfg = c.yellow, fg = tc.yellow },
  -- DevIconMts              = { ctermfg = c.blue, fg = tc.blue },
  -- DevIconTypeScript       = { ctermfg = c.blue, fg = tc.blue },
  -- DevIconRs               = { ctermfg = c.red, fg = tc.red },
  -- DevIconPsScriptfile     = { ctermfg = c.green, fg = tc.green },
  -- DevIconConfiguration    = { ctermfg = c.red, fg = tc.red },
  -- DevIconJson             = { ctermfg = c.yellow, fg = tc.yellow },
  -- DevIconJson5            = { ctermfg = c.yellow, fg = tc.yellow },
  -- DevIconJsonc            = { ctermfg = c.yellow, fg = tc.yellow },
}
